StageConstants = {
	LEVELS = 3,

	SPAWN_TIMEOUT_LEVEL_1 = 2, --seconds
	SPAWN_TIMEOUT_LEVEL_2 = 1, 
	SPAWN_TIMEOUT_LEVEL_3 = 0.5,

	PROGRAMMER_GOAL_LEVEL_1 = 10,
	PROGRAMMER_GOAL_LEVEL_2 = 5,
	PROGRAMMER_GOAL_LEVEL_3 = 2,

	STAGE_TIME_LEVEL_1 = 30,--seconds
	STAGE_TIME_LEVEL_2 = 60,--seconds
	STAGE_TIME_LEVEL_3 = 180,--seconds

	OBSTACLE_WIDTH = 20,
	OBSTACLE_HEIGHT = 20,

	OBSTACLE_SPEED = 5,
	OBSTACLE_MARGIN = 20*0.5,

	PROGRAMMER_WIDTH = 22,
	PROGRAMMER_HEIGHT = 22,
	PROGRAMMER_SPEED = 10,

	HERO_RADIUS = 10,
	HERO_SPEED = 150,

	FLING_COEFFICIENT = 2,
	HERO_SPEED_DECREASE = 0.5,
	

	CRASH_COEFFICIENT = 0.5,

	HERO_FORCE_DECREASE = 0.8,

	VANISH_PROB = 0.05,
	FADE_TIME = 2
}