StageConstants = {
	SPAWN_TIMEOUT_LEVEL_1 = 2, --seconds
	SPAWN_TIMEOUT_LEVEL_2 = 1, 
	SPAWN_TIMEOUT_LEVEL_3 = 0.5,

	PROGRAMMER_GOAL_LEVEL_1 = 10,
	PROGRAMMER_GOAL_LEVEL_2 = 8,
	PROGRAMMER_GOAL_LEVEL_3 = 5,

	STAGE_TIME_LEVEL_1 = 30,--seconds
	STAGE_TIME_LEVEL_2 = 30,--seconds
	STAGE_TIME_LEVEL_3 = 30,--seconds

	OBSTACLE_WIDTH = 20,
	OBSTACLE_HEIGHT = 20,

	OBSTACLE_SPEED = 100,
	OBSTACLE_MARGIN = 20*0.5,

	PROGRAMMER_WIDTH = 22,
	PROGRAMMER_HEIGHT = 22,
	PROGRAMMER_SPEED = 150,

	HERO_RADIUS = 10,
	HERO_SPEED = 150,
}